services:

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt-broker

    ports:
      - "1883:1883"

    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf


  postgres:
    image: postgres:16
    container_name: postgres-db

    environment:
      POSTGRES_USER: iotuser
      POSTGRES_PASSWORD: iotpassword
      POSTGRES_DB: iotdb

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  postgres_data: